### ISSUE TITLE
モバイル環境への通知試験（android／iPhone）

### ISSUE THREAD

**Issue by tkameyamax** [tkame123/study_javascript_designpattern#11]

**Comment by tkame123** [comment]
Android
https://developers.google.com/web/updates/2015/05/notifying-you-of-changes-to-notifications?hl=en

**Comment by tkame123** [comment]
`Notification` による通知がAndroidで非対応になっている模様、代替で提示されている　` ServiceWorkerRegistration.getNotifications() ` がServiceWorkerでの動作のため、修正を実施

FirebaseMessageSDKで用意されている、`messaging.setBackgroundMessageHandler`  や `messaging.onMessage` を使った実装がわかっていないが一旦Close
